### ISSUE TITLE
Fix compatibility with Bazel 6.0

### ISSUE THREAD

**Issue by arunkumar9t2** [grab/grab-bazel-common#77]
```bash
ERROR: Traceback (most recent call last):
        File "/Users/mohammad.khaleghi/StudioProjects/grab/grab-bazel-common/WORKSPACE", line 21, column 20, in <toplevel>
                kotlin_repositories()
        File "/private/var/tmp/_bazel_mohammad.khaleghi/5dd2ed53bdcf2520d3af415e6cc5931f/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl", line 96, column 21, in kotlin_repositories
                rules_repository(
Error in repository_rule: invalid user-provided repo name '': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter
ERROR: Error computing the main repository mapping: at /private/var/tmp/_bazel_mohammad.khaleghi/5dd2ed53bdcf2520d3af415e6cc5931f/external/io_bazel_rules_kotlin/kotlin/core.bzl:2:5: at /private/var/tmp/_bazel_mohammad.khaleghi/5dd2ed53bdcf2520d3af415e6cc5931f/external/io_bazel_rules_kotlin/kotlin/internal/opts. 
```

- [x] Update rules kotlin
- [x] Remote deprecated bazelrc entries

**Comment by arunsampathkumar-grabtaxi** [comment]
6.3.2 is available of HEAD
